---

- name: Build new EE
  hosts: localhost
  connection: local
  gather_facts: true
  tags: buildee
  vars_files:
    - "{{ playbook_dir }}/.vault.yml"

  pre_tasks:
    - name: Assert that needed vars are supplied
      ansible.builtin.assert:
        that:
          - ee_vars_file is defined
          - ee_vars_file | length > 0
        fail_msg: "You must define ee_vars_file!"

    - name: "Include EE vars: {{ ee_vars_file | basename }}"
      ansible.builtin.include_vars:
        file: "{{ ee_vars_file }}"

  roles:
    - build_ee
