---
- name: Build new EE
  hosts: localhost
  connection: local
  gather_facts: true
  tags: buildee
  vars_files:
    - "{{ playbook_dir }}/.vault.yml"

  pre_tasks:
    - name: Assert that needed vars are supplied
      ansible.builtin.assert:
        that:
          - ee_vars_folder is defined
          - ee_vars_folder | length > 0
        fail_msg: "You must define ee_vars_folder!"

    - name: Override build path (so I can push to git repo)
      ansible.builtin.set_fact:
        build_ee_dest_dir: "vars/{{ ee_vars_folder }}/__build"

    - name: "Include EE vars: {{ ee_vars_folder | basename }}"
      ansible.builtin.include_vars:
        file: "vars/{{ ee_vars_folder }}/vars.yml"

  roles:
    - build_ee
