---
- name: Build single EE
  hosts: localhost
  connection: local
  gather_facts: true
  tags: buildee
  vars_files:
    - "{{ playbook_dir }}/.vault.yml"

  pre_tasks:
    - name: Assert that needed vars are supplied
      ansible.builtin.assert:
        that:
          - ee_vars_folder is defined
          - ee_vars_folder | length > 0
        fail_msg: "You must define ee_vars_folder!"

  tasks:
    - name: Include build_ee tasks file
      vars:
        execution_environments:
          - "{{ ee_vars_folder }}"
      loop: "{{ execution_environments }}"
      loop_control:
        loop_var: execution_environment
        index_var: ee_idx
      ansible.builtin.include_tasks:
        file: tasks/build_ee.yml
...
