---
collections:
- name: https://github.com/redhat-cop/infra.controller_configuration.git
  type: git
  version: devel
- name: ansible.controller
  version: '>=4.5.0,<4.6.0'
- name: https://github.com/redhat-cop/infra.support_assist.git
  type: git
  version: devel
- name: ansible.platform
  version: '>=2.6,<2.7'
- /etc/ansible/lennysh-aap_credentials-0.1.0-devel.tar.gz
