---
build_ee_version: 3
build_ee_dest_dir: "{{ playbook_dir }}/_build/"
build_ee_bindep_file: bindep.txt
build_ee_python_requirements_file: requirements.txt
build_ee_galaxy_requirements_file: requirements.yml
build_ee_push_to_registry: true
