---
collections:
- name: infra.aap_configuration
- name: infra.aap_configuration_extended
- name: ansible.controller
  version: '>=4.7,<4.8'
- name: ansible.platform
  version: '>=2.6,<2.7'
- name: ansible.eda
- name: ansible.hub
- name: community.postgresql
